### ISSUE TITLE
firmware service does not have latest rotate hex

### ISSUE THREAD

**Issue by programmarchy** [modrobotics/node-cubelets#5]
Was downgrading some blocks and ran into some issues with rotates.

This cubelet:
http://cubelets-programming.appspot.com/api/cubelet_info/?ids=204329

Returns 5.0 for latest firmware version, but this doesn't exist on firmware server:

http://cubelets-programming.appspot.com/static/firmware/pic/5.0/46.hex

404

The newest firmware version I could find was 2.4:

http://cubelets-programming.appspot.com/static/firmware/pic/2.4/46.hex

**Comment by programmarchy** [comment]
pinging @ELundby45 do you know if 5.0 is really the latest rotate firmware version?

**Comment by ELundby45** [comment]
5.0 Means that it was put in the datastore as an imago Cubelet. I'll have to add a service to get the latest OS3 version for a Cubelet in the datastore as imago already.

**Comment by programmarchy** [comment]
This is just a temporary thing to convert OS 4 stock to OS 3. Can do it manually for now. Going to downgrade to http://cubelets-programming.appspot.com/static/firmware/pic/2.6/46.hex

Closing for now. Thanks!
