### ISSUE TITLE
App is frozen in iOS10.

### ISSUE THREAD

**Issue by wiadev** [modrobotics/node-cubelets#6]
Hi @modrobotics
first of all, Thanks for the product.
I've enjoyed using it until iOS 9.3.5 but after upgrading iOS 10, the app started to be frozen.

I've debugged myself and found a code for it.

```
var upgrade = new Upgrade(client)
 upgrade.detectIfNeeded(function (err, needsUpgrade) {});
```

the above detectIfNeeded is the one which is not working on iOS10.

Any suggestion to fix this?

Thanks.

**Comment by ELundby45** [comment]
Thanks for looking into it @wiadev 

Turns out this was due to https://github.com/feross/buffer/issues/136

We've updated the buffer module and all is well again. You should see an update in iTunes.
